"""empty message

Revision ID: 02a6be3b8942
Revises: dc78711dd75b
Create Date: 2024-11-25 15:47:11.765411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a6be3b8942'
down_revision = 'dc78711dd75b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selected_ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selected_ingredient', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
