"""empty message

Revision ID: 21a281c7ad3a
Revises: 491b0320ef15
Create Date: 2024-12-04 12:29:25.141168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21a281c7ad3a'
down_revision = '491b0320ef15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('ingredients', sa.String(length=500), nullable=True),
    sa.Column('steps', sa.Text(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('recipe_suggestion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_suggestion',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('ingredients', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('steps', mysql.TEXT(), nullable=True),
    sa.Column('ingredient_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name='recipe_suggestion_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('recipe_suggestions')
    # ### end Alembic commands ###
