"""Add category to SelectedIngredient

Revision ID: 27878ab36495
Revises: 3a049bd24af9
Create Date: 2024-11-25 11:57:14.410118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27878ab36495'
down_revision = '3a049bd24af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selected_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selected_ingredient')
    # ### end Alembic commands ###
