"""empty message

Revision ID: 392eca79e80f
Revises: 02a6be3b8942
Create Date: 2024-11-25 15:49:28.485747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392eca79e80f'
down_revision = '02a6be3b8942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selected_ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selected_ingredient', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
