"""empty message

Revision ID: 412bb1e34ed7
Revises: b198a1bd522d
Create Date: 2024-11-25 14:40:30.826555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412bb1e34ed7'
down_revision = 'b198a1bd522d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selected_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selected_ingredient')
    # ### end Alembic commands ###
