"""empty message

Revision ID: 524574e2cfa7
Revises: 392eca79e80f
Create Date: 2024-11-25 15:53:33.850791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '524574e2cfa7'
down_revision = '392eca79e80f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selected_ingredient', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selected_ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
