"""Reset tables for better design

Revision ID: b198a1bd522d
Revises: 27878ab36495
Create Date: 2024-11-25 12:14:35.066961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b198a1bd522d'
down_revision = '27878ab36495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selected_ingredient', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selected_ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
